
os:
  - linux

dist: xenial

language: python

jobs:
  include:
    - stage: test
      script:
      - python -m pytest -v
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --tag python-docker .
      - docker images
      - docker tag python-docker:latest sreemaish/python-dynamo-webservice:latest
      - docker push sreemaish/python-dynamo-webservice:latest 
