version: '3'
services: 
    api-service:
        build: ./
        volumes: 
            - ./app
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
            aws_access_key_id: ${aws_access_key_id}
            aws_secret_access_key: ${aws_access_key_id}
            USERS_TABLE: ${USERS_TABLE}